# Generated by Django 3.1.5 on 2021-10-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_id',
            new_name='gameId',
        ),
        migrations.AddField(
            model_name='player',
            name='marks',
            field=models.TextField(null=True),
        ),
    ]
