# Generated by Django 3.1.5 on 2021-10-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20211015_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
