# Generated by Django 3.1.5 on 2021-10-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211015_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email_id',
            new_name='emailId',
        ),
    ]
