# Generated by Django 3.1.5 on 2021-10-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=15)),
                ('quizId', models.CharField(max_length=100)),
                ('questionNumber', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=500)),
                ('marks', models.IntegerField()),
                ('timer', models.IntegerField()),
            ],
        ),
    ]
