# Generated by Django 3.1.5 on 2021-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizId',
            field=models.IntegerField(),
        ),
    ]
